### ISSUE TITLE
SVG path not Unique for character > 25

### ISSUE THREAD

**Issue by naveen521kk** [leifgehrmann/pangocairocffi#19]
I'm from [Manim](https://github.com/manimcommunity/manim) were we this project for rendering Text. Now, here there is a problem.
We have a method to create a SVG file using this project and later that SVG file is parsed in as Mobject(more like numpy array). It is made so that each letter would represent a submobject(again a numpy array) where the user can manipulate the submobject also. Now, the problem here is the SVG file created using this project and cairocffi, the `number of SVG path != number of character` for total lenth of character is greater than 25(`>25`). `<25` works like a charm. 
On carefully examining it, it look like the path string of the last two character are concadinated (which is unexpected) and it looks like a bug for me. I expected that the `length of string = length of paths - number of space and line break` but it wasn't so, for `string length>25`.

## Reproducing Code

```py
import cairocffi
import pangocffi
import pangocairocffi
surface = cairocffi.SVGSurface("bug.svg", 600, 400)
context = cairocffi.Context(surface)
context.move_to(10, 10)
layout = pangocairocffi.create_layout(context)
layout.set_width(pangocffi.units_from_double(600))
fontdesc = pangocffi.FontDescription()
fontdesc.set_size(pangocffi.units_from_double(10))
layout.set_font_description(fontdesc)
layout.set_text("#This is some custom confl")
pangocairocffi.show_layout(context, layout)
surface.finish()
```
After running this I get a SVG file, `bug.zip`, packed in a zip file attached at end,
Here, there is 26 character on the whole and it has 4 white spaces. But there are only 25 paths defined as below.
```svg
<g style="fill:rgb(0%,0%,0%);fill-opacity:1;">
  <use xlink:href="#glyph0-1" x="10" y="22"/>
  <use xlink:href="#glyph0-2" x="21" y="22"/>
  <use xlink:href="#glyph0-3" x="30" y="22"/>
  <use xlink:href="#glyph0-4" x="39" y="22"/>
  <use xlink:href="#glyph0-5" x="43" y="22"/>
  <use xlink:href="#glyph0-6" x="50" y="22"/>
  <use xlink:href="#glyph0-4" x="54" y="22"/>
  <use xlink:href="#glyph0-5" x="58" y="22"/>
  <use xlink:href="#glyph0-6" x="65" y="22"/>
  <use xlink:href="#glyph0-5" x="69" y="22"/>
  <use xlink:href="#glyph0-7" x="76" y="22"/>
  <use xlink:href="#glyph0-8" x="84" y="22"/>
  <use xlink:href="#glyph0-9" x="97" y="22"/>
  <use xlink:href="#glyph0-6" x="105" y="22"/>
  <use xlink:href="#glyph0-10" x="109" y="22"/>
  <use xlink:href="#glyph0-11" x="116" y="22"/>
  <use xlink:href="#glyph0-5" x="125" y="22"/>
  <use xlink:href="#glyph0-12" x="132" y="22"/>
  <use xlink:href="#glyph0-7" x="137" y="22"/>
  <use xlink:href="#glyph0-8" x="145" y="22"/>
  <use xlink:href="#glyph0-6" x="158" y="22"/>
  <use xlink:href="#glyph0-10" x="162" y="22"/>
  <use xlink:href="#glyph0-7" x="169" y="22"/>
  <use xlink:href="#glyph0-13" x="177" y="22"/>
  <use xlink:href="#glyph0-14" x="186" y="22"/>
</g>
```
Where it should 26 though. On further examining I found that 
```svg
<symbol overflow="visible" id="glyph0-14">
<path style="stroke:none;" d="M 4.773438 -10.128906 L 7.355469 -10.128906 L 7.355469 -0.691406 L 8.496094 -0.691406 L 8.496094 0 L 5.011719 0 L 5.011719 -0.691406 L 6.160156 -0.691406 L 6.160156 -9.441406 L 4.757813 -9.441406 C 4.050781 -9.4375 3.550781 -9.296875 3.261719 -9.015625 C 2.96875 -8.730469 2.824219 -8.25 2.824219 -7.570313 L 2.824219 -6.921875 L 4.746094 -6.921875 L 4.746094 -6.222656 L 2.824219 -6.222656 L 2.824219 -0.691406 L 3.957031 -0.691406 L 3.957031 0 L 0.480469 0 L 0.480469 -0.691406 L 1.628906 -0.691406 L 1.628906 -6.222656 L 0.480469 -6.222656 L 0.480469 -6.921875 L 1.628906 -6.921875 L 1.628906 -7.546875 C 1.628906 -8.417969 1.886719 -9.066406 2.40625 -9.492188 C 2.921875 -9.914063 3.710938 -10.125 4.773438 -10.128906 Z M 4.773438 -10.128906 "/>
</symbol>
```
the above one represent two charaters `fl`. But it should actually be one character `l` alone. This is the main issue which simply broke many parts of Manim Code. 

I had to make an here issue to make a reference in Pango Repo ;-) https://gitlab.gnome.org/GNOME/pango/-/issues/516
[bug.zip](https://github.com/leifgehrmann/pangocairocffi/files/5552007/bug.zip)

Pango Version: 
```py
>>> pangocffi.pango_version_string()
'1.46.1'
```
On my Windows 10, with Pango provided by msys2 project.

**Comment by leifgehrmann** [comment]
If you really want to disable ligatures, you can do this by instead using `set_markup` and configuring the font-features like this:

```
layout.set_markup("<span font_features='liga=0'>#This is some custom confl</span>")
```

Which will render 5 glyphs:

<img width="733" alt="Screenshot 2020-11-17 at 08 47 46" src="https://user-images.githubusercontent.com/3501061/99367204-92abff00-28b1-11eb-9e6c-4faca4d2773f.png">

For more information on pango's markup, see: https://developer.gnome.org/pango/stable/pango-Markup.html

If that still doesn't work with your font, there are other types of ligatures according to Wikipedia: https://en.wikipedia.org/wiki/Orthographic_ligature#Computer_typesetting

> In OpenType, there are standard `liga`, historical `hlig`, contextual `clig`, discretionary `dlig` and required `rlig` ligatures.

Strong note of caution though... If people are using a particular font with special ligatures, or languages that are heavily dependant on ligatures, the rendered text may look unexpected to them. I would recommend finding an alternative way to count the number of glyphs in a string, rather than looking at the number of characters in a string. I think the easiest way to do this would be to pre-render the glyphs in a different cairo context and count the glyphs, but that would be computationally more expensive I suppose.

**Comment by naveen521kk** [comment]
I just did it with the patch https://github.com/naveen521kk/manim/commit/ab239c22b326d6010957f0bb57289a0736a844ab
Where I used the method `pangocairocffi.layout_path(context, layout)` to render each letter and then write it to the context which seemed satisfying but could have bugs there. That took me a while to figure it out. But the problem I think could possibly break is `rtl` texts.

I am no going to play with ligatures here, because the reason `Manim` switched from cairo toy API to Pango for rendering text is to support right to left text rendering.

**Comment by leifgehrmann** [comment]
I'm not quite sure what you mean, but to answer your original question about whether this is considered a bug, it's clearly intended by the font that `fl` will be converted to the glyph `ﬂ`, and that will mean there are only 25 glyphs in the pango output of `#This is some custom confl`, and not 26. I would expect the exact same thing to happen with the string `Offices` (It's 7 characters/bytes long, but only 6 glyphs)

<img width="814" alt="Screenshot 2020-11-17 at 21 19 12" src="https://user-images.githubusercontent.com/3501061/99451842-b7888c80-291a-11eb-8f7b-880be4a39aa9.png">

Can you elaborate a bit more how manim works? Why are you looping over each byte in the string? Can you not iterate over the number of glyphs in the output of Pango? Or do you need to match the glyph with the associated byte in the string?

**Comment by naveen521kk** [comment]
> Can you elaborate a bit more how manim works?

What manim does is create a SVG file,with the text there, using Pango and later parse it using [`SVGMobject`](https://github.com/ManimCommunity/manim/blob/e51d7740783aa41ce25cb31665e7bcb7f751a16f/manim/mobject/svg/svg_mobject.py#L33) which is in a way not so good, as it simply ignores the style attribute in the SVG file and simply not parses many things and deliberately ignore some. Finally, after parsing it, it draws each paths string on a Cairo Surface and finally converts them to NumPy arrays.

> Why are you looping over each byte in the string? Can you not iterate over the number of glyphs in the output of Pango? Or do you need to match the glyph with the associated byte in the string?

Now, since it ignores the colours, I had to make it so that colours are later added by editing the NumPy array the `SVGMobject` generates(which works actually, there are already methods defined for it). Now,here is the problem. The `SVGMobject` returns each path strings which are not empty as `submobjects`, which can be used to manipulate the colours, here the characters(text) and the `submobject` not being same if it contains  space or the case like above, it simply fails to colour it properly. The `gen_chars` method which was defined in that commit(see previous comment) actually solves the part of spaces as it create a new object in places where there is space. But that method simply fails because of these ligratures. 
Finally, it fails the ability to show syntax highlighting. which heavily depends on this. One thing which can be done here is to not use SVGMobject and instead directly use Pango using Cairo to create numpy arrays. That could solve this problem but requires a lot of work as in `pangocffi` doesn't yet, support `PangoAttribute`.

> Or do you need to match the glyph with the associated byte in the string?

That was the goal I wanted, but moving from parsing the SVG file would be a lot better. Need to look into it though.

**Comment by naveen521kk** [comment]
Its not a bug on pango's side so closing it. ;-)
Something need to be revamped in manim's side.
