### ISSUE TITLE
Missing PangoCairoFontMap.get_default

### ISSUE THREAD

**Issue by qwenger** [leifgehrmann/pangocairocffi#25]
The docstring of `PangoCairoFontMap` mentions the method `get_default` (https://github.com/leifgehrmann/pangocairocffi/blob/master/pangocairocffi/font_map.py#L30), but it does not seem to be implemented yet.

**Comment by leifgehrmann** [comment]
Thanks for spotting that! It's now implemented in v0.6.0.
